---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	orchestrator(orchestrator)
	financial(financial)
	news(news)
	risk(risk)
	rag(rag)
	performance(performance)
	__end__([<p>__end__</p>]):::last
	__start__ --> orchestrator;
	financial --> performance;
	news --> performance;
	orchestrator --> financial;
	orchestrator --> news;
	orchestrator --> rag;
	orchestrator --> risk;
	rag --> performance;
	risk --> performance;
	performance --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
